### ISSUE TITLE
How to get the mod going? Any prerequisites to download?

### ISSUE THREAD

**Issue by TheGreat09123** [L1Z3/BOTW-Multiplayer-Steam-Deck#40]
Hello, I hate to ask this as I am sure it has been answered somewhere else, but I am new here and don't know where to get started at all. I have BOTW files (Game,DLC, and Update), how do I get Cemu going on the deck? After that, how do I get the script to work and install the multiplayer mod?
Any help would be greatly appreciated!

**Comment by L1Z3** [comment]
Hey! This script is still in its early stages and may break! The only prereq for this script currently is having Cemu and the game files. However, all downloads for the mod itself have been taken down (presumably due to issues with Nintendo) and we can't provide those mod files for you, so the script won't work until that's resolved (unless you have the mod files from elsewhere).

Once the script is more stable, we plan to have a full tutorial for how to use it, but that won't be much use until the mod downloads are back up.

**Comment by L1Z3** [comment]
That being said, if you want to try getting the script running, our early version of the complete script is [here](https://raw.githubusercontent.com/L1Z3/BOTW-Multiplayer-Steam-Deck/feature/elj/install-script/install.sh). Open that page in your browser in desktop mode, right click, and save it as install.sh. 

From there, open a terminal and `cd` to your Downloads folder. Run `chmod +x install.sh` to give the script permissions to run. Then `./install.sh`. Note that until the mod downloads are back up, the script *will not* work as intended unless you place the mod files in `/home/deck/.local/botwminstaller/BreathOfTheWildMultiplayer`.

**Comment by L1Z3** [comment]
Oh I see you also asked for how to get Cemu going on Deck—for that, there should be some tutorials on YouTube! The simplest way is probably [EmuDeck](https://www.emudeck.com/).

**Comment by TheGreat09123** [comment]
Thank you so much for the pointers, yeah saw the announcement on the discord but was hoping files on GitHub wouldn't be affected. I do have files stored locally on my Windows machine, so when I get Cemu/BOTW up and running is there a way to point the script toward that local directory if I SSH that build to my deck?

**Comment by L1Z3** [comment]
Yes! Copy the mod files (multiplayer exe, BNPs folder, Version.txt, etc) to `/home/deck/.local/share/botwminstaller/BreathOfTheWildMultiplayer`. Then the script *should* work, assuming something doesn't break on our end!

**Comment by TheGreat09123** [comment]
Thank you so much! I don’t have my deck on me right now, but I’ll do that when I get home and see if it works :)

**Comment by TheGreat09123** [comment]
Ok, so ran it on my deck and all was going well until after I was asked which steam user id I wanted to use, I got this error.
Successfully closed 'Steam'.
User IDs:
1. _(not sure if this is public but redacted regardless)_
Enter the number of the user ID you want to use: 1
Traceback (most recent call last):
  File "/home/deck/.local/share/botwminstaller/installer/main.py", line 48, in <module>
    main()
  File "/home/deck/.local/share/botwminstaller/installer/main.py", line 28, in main
    prefix_app_id, user_id = generate_steam_shortcut()
  File "/home/deck/.local/share/botwminstaller/installer/utils/steam.py", line 273, in generate_steam_shortcut
    set_proton_version(prefix_app_id)
  File "/home/deck/.local/share/botwminstaller/installer/utils/steam.py", line 184, in set_proton_version
    data["InstallConfigStore"]["Software"]["Valve"]["Steam"]["CompatToolMapping"][str(prefix_app_id)] = \
KeyError: 'CompatToolMapping'
Any idea what might be causing this? entirely could be on my end, but I couldn't find any issues with my BOTW install.
Thanks!

**Comment by L1Z3** [comment]
Oop yes! This looks to be an edge case we forgot to cover, sorry about that! Can you try opening Steam, finding the newly created "Breath of the Wild Multiplayer" shortcut, going to properties, and enabling Proton Experimental in the compatibility options? After that, try running the script again.

**Comment by TheGreat09123** [comment]
I'll try that, thanks!

**Comment by TheGreat09123** [comment]
It worked flawlessly! Thank you so much for your help, and I'd just like to say I appreciate how great of a tool this is, not having to fumble around with BCML and proton and stuff, its awesome. It's frankly more straightforward than the windows installation, and in my opinion, they should have implemented a solution like this in the first place on windows.
Again, thank you for your help and such an amazing piece of software!

**Comment by L1Z3** [comment]
Awww you're very welcome!!! I've had a great time working on it! I'm glad it helped :)

And yeah a nice install on Windows would be nice... maybe we'll do that too ;) (#30)
